import 'package:desktopApp/responsive_helper.dart';
import 'package:desktopApp/view_widget.dart';
import 'package:dynamic_theme/dynamic_theme.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:responsive_framework/responsive_framework.dart';

void main() {
  runApp(MyApp());
}

ThemeData getTheme({TextTheme? theme, required bool isLight}) {
  if (theme == null) theme = GoogleFonts.nunitoTextTheme();
  return new ThemeData(
      brightness: isLight ? Brightness.light : Brightness.dark,
      scaffoldBackgroundColor: Colors.red.shade400,
      textTheme: theme);
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: DynamicTheme(
      data: (Brightness brightness) =>
          getTheme(isLight: brightness == Brightness.light),
      themedWidgetBuilder: (context, data) {
        return ResponsiveWrapper(
          shrinkWrap: true,
          mediaQueryData: MediaQuery.of(context),
          minWidth: 400,
          child: MaterialApp(
            theme: data,
            home: MyHomePage(title: 'Fontism'),
          ),
          breakpoints: [
            ResponsiveBreakpoint.resize(480, name: MOBILE),
            ResponsiveBreakpoint.autoScale(800, name: TABLET),
            ResponsiveBreakpoint.resize(1000, name: DESKTOP),
          ],
        );
      },
    ));
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, this.title}) : super(key: key);
  final String? title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool isLight = true;

  void updateFont(TextTheme theme) {
    DynamicTheme.of(context)!
        .setThemeData(getTheme(theme: theme, isLight: isLight));
  }

  Widget drawerWidget() {
    return Drawer(child: Builder(builder: (context) {
      return ListView.builder(
          itemCount: themes.length,
          itemBuilder: (context, index) {
            String key = themes.keys.elementAt(index);
            TextTheme theme = themes[key]!();
            return Theme(
              data: getTheme(theme: theme, isLight: isLight),
              child: ListTile(
                  key: UniqueKey(),
                  onTap: () {
                    updateFont(theme);
                  },
                  title: Text(key)),
            );
          });
    }));
  }

  Widget bodyWidget() {
    return ViewWidget();
  }

  Widget bottomNavigationWidget() {
    return BottomNavigationBar(
      currentIndex: 1,
      selectedItemColor: Colors.blue,
      unselectedItemColor: Colors.grey,
      items: [
        BottomNavigationBarItem(icon: Icon(Icons.home), label: 'Home'),
        BottomNavigationBarItem(icon: Icon(Icons.home), label: 'Home'),
        BottomNavigationBarItem(icon: Icon(Icons.home), label: 'Home'),
        BottomNavigationBarItem(icon: Icon(Icons.home), label: 'Home')
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    return ResponsiveHelper(
        webWidget: Scaffold(
          appBar: AppBar(
            title: Text(widget.title!),
          ),
          body: Row(
            children: <Widget>[drawerWidget(), Expanded(child: bodyWidget())],
          ),
          bottomNavigationBar: bottomNavigationWidget(),
        ),
        mobileWidget: Scaffold(
          appBar: AppBar(
            title: Text(widget.title!),
          ),
          drawer: drawerWidget(),
          body: bodyWidget(),
          bottomNavigationBar: bottomNavigationWidget(),
        ));
  }

  Map<String, TextTheme Function([TextTheme?])> themes = {
    'ABeeZee': GoogleFonts.aBeeZeeTextTheme,
    'Abel': GoogleFonts.abelTextTheme,
    'Abhaya Libre': GoogleFonts.abhayaLibreTextTheme,
    'Abril Fatface': GoogleFonts.abrilFatfaceTextTheme,
    'Aclonica': GoogleFonts.aclonicaTextTheme,
    'Acme': GoogleFonts.acmeTextTheme,
    'Actor': GoogleFonts.actorTextTheme,
    'Adamina': GoogleFonts.adaminaTextTheme,
    'Advent Pro': GoogleFonts.adventProTextTheme,
    'Aguafina Script': GoogleFonts.aguafinaScriptTextTheme,
    'Akronim': GoogleFonts.akronimTextTheme,
    'Aladin': GoogleFonts.aladinTextTheme,
    'Alata': GoogleFonts.alataTextTheme,
    'Alatsi': GoogleFonts.alatsiTextTheme,
    'Aldrich': GoogleFonts.aldrichTextTheme,
    'Alef': GoogleFonts.alefTextTheme,
    'Alegreya': GoogleFonts.alegreyaTextTheme,
    'Alegreya SC': GoogleFonts.alegreyaScTextTheme,
    'Alegreya Sans': GoogleFonts.alegreyaSansTextTheme,
    'Alegreya Sans SC': GoogleFonts.alegreyaSansScTextTheme,
    'Aleo': GoogleFonts.aleoTextTheme,
    'Alex Brush': GoogleFonts.alexBrushTextTheme,
    'Alfa Slab One': GoogleFonts.alfaSlabOneTextTheme,
    'Alice': GoogleFonts.aliceTextTheme,
    'Alike': GoogleFonts.alikeTextTheme,
    'Alike Angular': GoogleFonts.alikeAngularTextTheme,
    'Allan': GoogleFonts.allanTextTheme,
    'Allerta': GoogleFonts.allertaTextTheme,
    'Allerta Stencil': GoogleFonts.allertaStencilTextTheme,
    'Allura': GoogleFonts.alluraTextTheme,
    'Almarai': GoogleFonts.almaraiTextTheme,
    'Almendra': GoogleFonts.almendraTextTheme,
    'Almendra Display': GoogleFonts.almendraDisplayTextTheme,
    'Almendra SC': GoogleFonts.almendraScTextTheme,
    'Amarante': GoogleFonts.amaranteTextTheme,
    'Amaranth': GoogleFonts.amaranthTextTheme,
    'Amatic SC': GoogleFonts.amaticScTextTheme,
    'Amatica SC': GoogleFonts.amaticaScTextTheme,
    'Amethysta': GoogleFonts.amethystaTextTheme,
    'Amiko': GoogleFonts.amikoTextTheme,
    'Amiri': GoogleFonts.amiriTextTheme,
    'Amita': GoogleFonts.amitaTextTheme,
    'Anaheim': GoogleFonts.anaheimTextTheme,
    'Andada': GoogleFonts.andadaTextTheme,
    'Andika': GoogleFonts.andikaTextTheme,
    'Annie Use Your Telescope': GoogleFonts.annieUseYourTelescopeTextTheme,
    'Anonymous Pro': GoogleFonts.anonymousProTextTheme,
    'Antic': GoogleFonts.anticTextTheme,
    'Antic Didone': GoogleFonts.anticDidoneTextTheme,
    'Antic Slab': GoogleFonts.anticSlabTextTheme,
    'Anton': GoogleFonts.antonTextTheme,
    'Arapey': GoogleFonts.arapeyTextTheme,
    'Arbutus': GoogleFonts.arbutusTextTheme,
    'Arbutus Slab': GoogleFonts.arbutusSlabTextTheme,
    'Architects Daughter': GoogleFonts.architectsDaughterTextTheme,
    'Archivo': GoogleFonts.archivoTextTheme,
    'Archivo Black': GoogleFonts.archivoBlackTextTheme,
    'Archivo Narrow': GoogleFonts.archivoNarrowTextTheme,
    'Aref Ruqaa': GoogleFonts.arefRuqaaTextTheme,
    'Arima Madurai': GoogleFonts.arimaMaduraiTextTheme,
    'Arimo': GoogleFonts.arimoTextTheme,
    'Arizonia': GoogleFonts.arizoniaTextTheme,
    'Armata': GoogleFonts.armataTextTheme,
    'Arsenal': GoogleFonts.arsenalTextTheme,
    'Artifika': GoogleFonts.artifikaTextTheme,
    'Arvo': GoogleFonts.arvoTextTheme,
    'Arya': GoogleFonts.aryaTextTheme,
    'Asap': GoogleFonts.asapTextTheme,
    'Asar': GoogleFonts.asarTextTheme,
    'Asset': GoogleFonts.assetTextTheme,
    'Assistant': GoogleFonts.assistantTextTheme,
    'Astloch': GoogleFonts.astlochTextTheme,
    'Asul': GoogleFonts.asulTextTheme,
    'Athiti': GoogleFonts.athitiTextTheme,
    'Atma': GoogleFonts.atmaTextTheme,
    'Atomic Age': GoogleFonts.atomicAgeTextTheme,
    'Aubrey': GoogleFonts.aubreyTextTheme,
    'Audiowide': GoogleFonts.audiowideTextTheme,
    'Autour One': GoogleFonts.autourOneTextTheme,
    'Average': GoogleFonts.averageTextTheme,
    'Average Sans': GoogleFonts.averageSansTextTheme,
    'Averia Gruesa Libre': GoogleFonts.averiaGruesaLibreTextTheme,
    'Averia Libre': GoogleFonts.averiaLibreTextTheme,
    'Averia Sans Libre': GoogleFonts.averiaSansLibreTextTheme,
    'Averia Serif Libre': GoogleFonts.averiaSerifLibreTextTheme,
    'B612': GoogleFonts.b612TextTheme,
    'B612 Mono': GoogleFonts.b612MonoTextTheme,
    'Bad Script': GoogleFonts.badScriptTextTheme,
    'Bahiana': GoogleFonts.bahianaTextTheme,
    'Bahianita': GoogleFonts.bahianitaTextTheme,
    'Bai Jamjuree': GoogleFonts.baiJamjureeTextTheme,
    'Baloo': GoogleFonts.balooTextTheme,
    'Baloo Bhai': GoogleFonts.balooBhaiTextTheme,
    'Baloo Bhaijaan': GoogleFonts.balooBhaijaanTextTheme,
    'Baloo Bhaina': GoogleFonts.balooBhainaTextTheme,
    'Baloo Chettan': GoogleFonts.balooChettanTextTheme,
    'Baloo Da': GoogleFonts.balooDaTextTheme,
    'Baloo Paaji': GoogleFonts.balooPaajiTextTheme,
    'Baloo Tamma': GoogleFonts.balooTammaTextTheme,
    'Baloo Tammudu': GoogleFonts.balooTammuduTextTheme,
    'Baloo Thambi': GoogleFonts.balooThambiTextTheme,
    'Balthazar': GoogleFonts.balthazarTextTheme,
    'Bangers': GoogleFonts.bangersTextTheme,
    'Barlow': GoogleFonts.barlowTextTheme,
    'Barlow Condensed': GoogleFonts.barlowCondensedTextTheme,
    'Barlow Semi Condensed': GoogleFonts.barlowSemiCondensedTextTheme,
    'Barriecito': GoogleFonts.barriecitoTextTheme,
    'Barrio': GoogleFonts.barrioTextTheme,
    'Basic': GoogleFonts.basicTextTheme,
    'Baskervville': GoogleFonts.baskervvilleTextTheme,
    'Baumans': GoogleFonts.baumansTextTheme,
    'Be Vietnam': GoogleFonts.beVietnamTextTheme,
    'Bebas Neue': GoogleFonts.bebasNeueTextTheme,
    'Belgrano': GoogleFonts.belgranoTextTheme,
    'Bellefair': GoogleFonts.bellefairTextTheme,
    'Belleza': GoogleFonts.bellezaTextTheme,
    'Bellota': GoogleFonts.bellotaTextTheme,
    'Bellota Text': GoogleFonts.bellotaTextTextTheme,
    'BenchNine': GoogleFonts.benchNineTextTheme,
    'Bentham': GoogleFonts.benthamTextTheme,
    'Berkshire Swash': GoogleFonts.berkshireSwashTextTheme,
    'Beth Ellen': GoogleFonts.bethEllenTextTheme,
    'Bevan': GoogleFonts.bevanTextTheme,
    'Big Shoulders Display': GoogleFonts.bigShouldersDisplayTextTheme,
    'Big Shoulders Text': GoogleFonts.bigShouldersTextTextTheme,
    'Bigelow Rules': GoogleFonts.bigelowRulesTextTheme,
    'Bigshot One': GoogleFonts.bigshotOneTextTheme,
    'Bilbo': GoogleFonts.bilboTextTheme,
    'Bilbo Swash Caps': GoogleFonts.bilboSwashCapsTextTheme,
    'BioRhyme': GoogleFonts.bioRhymeTextTheme,
    'BioRhyme Expanded': GoogleFonts.bioRhymeExpandedTextTheme,
    'Biryani': GoogleFonts.biryaniTextTheme,
    'Bitter': GoogleFonts.bitterTextTheme,
    'Black And White Picture': GoogleFonts.blackAndWhitePictureTextTheme,
    'Black Han Sans': GoogleFonts.blackHanSansTextTheme,
    'Black Ops One': GoogleFonts.blackOpsOneTextTheme,
    'Blinker': GoogleFonts.blinkerTextTheme,
    'Bonbon': GoogleFonts.bonbonTextTheme,
    'Boogaloo': GoogleFonts.boogalooTextTheme,
    'Bowlby One': GoogleFonts.bowlbyOneTextTheme,
    'Bowlby One SC': GoogleFonts.bowlbyOneScTextTheme,
    'Brawler': GoogleFonts.brawlerTextTheme,
    'Bree Serif': GoogleFonts.breeSerifTextTheme,
    'Bubblegum Sans': GoogleFonts.bubblegumSansTextTheme,
    'Bubbler One': GoogleFonts.bubblerOneTextTheme,
    'Buda': GoogleFonts.budaTextTheme,
    'Buenard': GoogleFonts.buenardTextTheme,
    'Bungee': GoogleFonts.bungeeTextTheme,
    'Bungee Hairline': GoogleFonts.bungeeHairlineTextTheme,
    'Bungee Inline': GoogleFonts.bungeeInlineTextTheme,
    'Bungee Outline': GoogleFonts.bungeeOutlineTextTheme,
    'Bungee Shade': GoogleFonts.bungeeShadeTextTheme,
    'Butcherman': GoogleFonts.butchermanTextTheme,
    'Butterfly Kids': GoogleFonts.butterflyKidsTextTheme,
    'Cabin': GoogleFonts.cabinTextTheme,
    'Cabin Condensed': GoogleFonts.cabinCondensedTextTheme,
    'Cabin Sketch': GoogleFonts.cabinSketchTextTheme,
    'Caesar Dressing': GoogleFonts.caesarDressingTextTheme,
    'Cagliostro': GoogleFonts.cagliostroTextTheme,
    'Cairo': GoogleFonts.cairoTextTheme,
    'Caladea': GoogleFonts.caladeaTextTheme,
    'Calistoga': GoogleFonts.calistogaTextTheme,
    'Calligraffitti': GoogleFonts.calligraffittiTextTheme,
    'Cambay': GoogleFonts.cambayTextTheme,
    'Cambo': GoogleFonts.camboTextTheme,
    'Candal': GoogleFonts.candalTextTheme,
    'Cantarell': GoogleFonts.cantarellTextTheme,
    'Cantata One': GoogleFonts.cantataOneTextTheme,
    'Cantora One': GoogleFonts.cantoraOneTextTheme,
    'Capriola': GoogleFonts.capriolaTextTheme,
    'Cardo': GoogleFonts.cardoTextTheme,
    'Carme': GoogleFonts.carmeTextTheme,
    'Carrois Gothic': GoogleFonts.carroisGothicTextTheme,
    'Carrois Gothic SC': GoogleFonts.carroisGothicScTextTheme,
    'Carter One': GoogleFonts.carterOneTextTheme,
    'Catamaran': GoogleFonts.catamaranTextTheme,
    'Caudex': GoogleFonts.caudexTextTheme,
    'Caveat': GoogleFonts.caveatTextTheme,
    'Caveat Brush': GoogleFonts.caveatBrushTextTheme,
    'Cedarville Cursive': GoogleFonts.cedarvilleCursiveTextTheme,
    'Ceviche One': GoogleFonts.cevicheOneTextTheme,
    'Chakra Petch': GoogleFonts.chakraPetchTextTheme,
    'Changa': GoogleFonts.changaTextTheme,
    'Changa One': GoogleFonts.changaOneTextTheme,
    'Chango': GoogleFonts.changoTextTheme,
    'Charm': GoogleFonts.charmTextTheme,
    'Charmonman': GoogleFonts.charmonmanTextTheme,
    'Chathura': GoogleFonts.chathuraTextTheme,
    'Chau Philomene One': GoogleFonts.chauPhilomeneOneTextTheme,
    'Chela One': GoogleFonts.chelaOneTextTheme,
    'Chelsea Market': GoogleFonts.chelseaMarketTextTheme,
    'Cherry Cream Soda': GoogleFonts.cherryCreamSodaTextTheme,
    'Cherry Swash': GoogleFonts.cherrySwashTextTheme,
    'Chewy': GoogleFonts.chewyTextTheme,
    'Chicle': GoogleFonts.chicleTextTheme,
    'Chilanka': GoogleFonts.chilankaTextTheme,
    'Chivo': GoogleFonts.chivoTextTheme,
    'Chonburi': GoogleFonts.chonburiTextTheme,
    'Cinzel': GoogleFonts.cinzelTextTheme,
    'Cinzel Decorative': GoogleFonts.cinzelDecorativeTextTheme,
    'Clicker Script': GoogleFonts.clickerScriptTextTheme,
    'Coda': GoogleFonts.codaTextTheme,
    'Coda Caption': GoogleFonts.codaCaptionTextTheme,
    'Codystar': GoogleFonts.codystarTextTheme,
    'Coiny': GoogleFonts.coinyTextTheme,
    'Combo': GoogleFonts.comboTextTheme,
    'Comfortaa': GoogleFonts.comfortaaTextTheme,
    'Comic Neue': GoogleFonts.comicNeueTextTheme,
    'Coming Soon': GoogleFonts.comingSoonTextTheme,
    'Concert One': GoogleFonts.concertOneTextTheme,
    'Condiment': GoogleFonts.condimentTextTheme,
    'Contrail One': GoogleFonts.contrailOneTextTheme,
    'Convergence': GoogleFonts.convergenceTextTheme,
    'Cookie': GoogleFonts.cookieTextTheme,
    'Copse': GoogleFonts.copseTextTheme,
    'Corben': GoogleFonts.corbenTextTheme,
    'Cormorant': GoogleFonts.cormorantTextTheme,
    'Cormorant Garamond': GoogleFonts.cormorantGaramondTextTheme,
    'Cormorant Infant': GoogleFonts.cormorantInfantTextTheme,
    'Cormorant SC': GoogleFonts.cormorantScTextTheme,
    'Cormorant Unicase': GoogleFonts.cormorantUnicaseTextTheme,
    'Cormorant Upright': GoogleFonts.cormorantUprightTextTheme,
    'Courgette': GoogleFonts.courgetteTextTheme,
    'Courier Prime': GoogleFonts.courierPrimeTextTheme,
    'Cousine': GoogleFonts.cousineTextTheme,
    'Coustard': GoogleFonts.coustardTextTheme,
    'Covered By Your Grace': GoogleFonts.coveredByYourGraceTextTheme,
    'Crafty Girls': GoogleFonts.craftyGirlsTextTheme,
    'Creepster': GoogleFonts.creepsterTextTheme,
    'Crete Round': GoogleFonts.creteRoundTextTheme,
    'Crimson Pro': GoogleFonts.crimsonProTextTheme,
    'Crimson Text': GoogleFonts.crimsonTextTextTheme,
    'Croissant One': GoogleFonts.croissantOneTextTheme,
    'Crushed': GoogleFonts.crushedTextTheme,
    'Cuprum': GoogleFonts.cuprumTextTheme,
    'Cute Font': GoogleFonts.cuteFontTextTheme,
    'Cutive': GoogleFonts.cutiveTextTheme,
    'Cutive Mono': GoogleFonts.cutiveMonoTextTheme,
    'DM Sans': GoogleFonts.dmSansTextTheme,
    'DM Serif Display': GoogleFonts.dmSerifDisplayTextTheme,
    'DM Serif Text': GoogleFonts.dmSerifTextTextTheme,
    'Damion': GoogleFonts.damionTextTheme,
    'Dancing Script': GoogleFonts.dancingScriptTextTheme,
    'Darker Grotesque': GoogleFonts.darkerGrotesqueTextTheme,
    'David Libre': GoogleFonts.davidLibreTextTheme,
    'Dawning of a New Day': GoogleFonts.dawningOfANewDayTextTheme,
    'Days One': GoogleFonts.daysOneTextTheme,
    'Dekko': GoogleFonts.dekkoTextTheme,
    'Delius': GoogleFonts.deliusTextTheme,
    'Delius Swash Caps': GoogleFonts.deliusSwashCapsTextTheme,
    'Delius Unicase': GoogleFonts.deliusUnicaseTextTheme,
    'Della Respira': GoogleFonts.dellaRespiraTextTheme,
    'Denk One': GoogleFonts.denkOneTextTheme,
    'Devonshire': GoogleFonts.devonshireTextTheme,
    'Dhurjati': GoogleFonts.dhurjatiTextTheme,
    'Didact Gothic': GoogleFonts.didactGothicTextTheme,
    'Diplomata': GoogleFonts.diplomataTextTheme,
    'Diplomata SC': GoogleFonts.diplomataScTextTheme,
    'Do Hyeon': GoogleFonts.doHyeonTextTheme,
    'Dokdo': GoogleFonts.dokdoTextTheme,
    'Domine': GoogleFonts.domineTextTheme,
    'Donegal One': GoogleFonts.donegalOneTextTheme,
    'Doppio One': GoogleFonts.doppioOneTextTheme,
    'Dorsa': GoogleFonts.dorsaTextTheme,
    'Dosis': GoogleFonts.dosisTextTheme,
    'Dr Sugiyama': GoogleFonts.drSugiyamaTextTheme,
    'Droid Sans': GoogleFonts.droidSansTextTheme,
    'Droid Sans Mono': GoogleFonts.droidSansMonoTextTheme,
    'Droid Serif': GoogleFonts.droidSerifTextTheme,
    'Duru Sans': GoogleFonts.duruSansTextTheme,
    'Dynalight': GoogleFonts.dynalightTextTheme,
    'EB Garamond': GoogleFonts.ebGaramondTextTheme,
    'Eagle Lake': GoogleFonts.eagleLakeTextTheme,
    'East Sea Dokdo': GoogleFonts.eastSeaDokdoTextTheme,
    'Eater': GoogleFonts.eaterTextTheme,
    'Economica': GoogleFonts.economicaTextTheme,
    'Eczar': GoogleFonts.eczarTextTheme,
    'El Messiri': GoogleFonts.elMessiriTextTheme,
    'Electrolize': GoogleFonts.electrolizeTextTheme,
    'Elsie': GoogleFonts.elsieTextTheme,
    'Elsie Swash Caps': GoogleFonts.elsieSwashCapsTextTheme,
    'Emblema One': GoogleFonts.emblemaOneTextTheme,
    'Emilys Candy': GoogleFonts.emilysCandyTextTheme,
    'Encode Sans': GoogleFonts.encodeSansTextTheme,
    'Encode Sans Condensed': GoogleFonts.encodeSansCondensedTextTheme,
    'Encode Sans Expanded': GoogleFonts.encodeSansExpandedTextTheme,
    'Encode Sans Semi Condensed': GoogleFonts.encodeSansSemiCondensedTextTheme,
    'Encode Sans Semi Expanded': GoogleFonts.encodeSansSemiExpandedTextTheme,
    'Engagement': GoogleFonts.engagementTextTheme,
    'Englebert': GoogleFonts.englebertTextTheme,
    'Enriqueta': GoogleFonts.enriquetaTextTheme,
    'Erica One': GoogleFonts.ericaOneTextTheme,
    'Esteban': GoogleFonts.estebanTextTheme,
    'Euphoria Script': GoogleFonts.euphoriaScriptTextTheme,
    'Ewert': GoogleFonts.ewertTextTheme,
    'Exo': GoogleFonts.exoTextTheme,
    'Exo 2': GoogleFonts.exo2TextTheme,
    'Expletus Sans': GoogleFonts.expletusSansTextTheme,
    'Fahkwang': GoogleFonts.fahkwangTextTheme,
    'Fanwood Text': GoogleFonts.fanwoodTextTextTheme,
    'Farro': GoogleFonts.farroTextTheme,
    'Farsan': GoogleFonts.farsanTextTheme,
    'Fascinate': GoogleFonts.fascinateTextTheme,
    'Fascinate Inline': GoogleFonts.fascinateInlineTextTheme,
    'Faster One': GoogleFonts.fasterOneTextTheme,
    'Fauna One': GoogleFonts.faunaOneTextTheme,
    'Faustina': GoogleFonts.faustinaTextTheme,
    'Federant': GoogleFonts.federantTextTheme,
    'Federo': GoogleFonts.federoTextTheme,
    'Felipa': GoogleFonts.felipaTextTheme,
    'Fenix': GoogleFonts.fenixTextTheme,
    'Finger Paint': GoogleFonts.fingerPaintTextTheme,
    'Fira Code': GoogleFonts.firaCodeTextTheme,
    'Fira Mono': GoogleFonts.firaMonoTextTheme,
    'Fira Sans': GoogleFonts.firaSansTextTheme,
    'Fira Sans Condensed': GoogleFonts.firaSansCondensedTextTheme,
    'Fira Sans Extra Condensed': GoogleFonts.firaSansExtraCondensedTextTheme,
    'Fjalla One': GoogleFonts.fjallaOneTextTheme,
    'Fjord One': GoogleFonts.fjordOneTextTheme,
    'Flamenco': GoogleFonts.flamencoTextTheme,
    'Flavors': GoogleFonts.flavorsTextTheme,
    'Fondamento': GoogleFonts.fondamentoTextTheme,
    'Fontdiner Swanky': GoogleFonts.fontdinerSwankyTextTheme,
    'Forum': GoogleFonts.forumTextTheme,
    'Francois One': GoogleFonts.francoisOneTextTheme,
    'Frank Ruhl Libre': GoogleFonts.frankRuhlLibreTextTheme,
    'Freckle Face': GoogleFonts.freckleFaceTextTheme,
    'Fredericka the Great': GoogleFonts.frederickaTheGreatTextTheme,
    'Fredoka One': GoogleFonts.fredokaOneTextTheme,
    'Fresca': GoogleFonts.frescaTextTheme,
    'Frijole': GoogleFonts.frijoleTextTheme,
    'Fruktur': GoogleFonts.frukturTextTheme,
    'Fugaz One': GoogleFonts.fugazOneTextTheme,
    'GFS Didot': GoogleFonts.gfsDidotTextTheme,
    'GFS Neohellenic': GoogleFonts.gfsNeohellenicTextTheme,
    'Gabriela': GoogleFonts.gabrielaTextTheme,
    'Gaegu': GoogleFonts.gaeguTextTheme,
    'Gafata': GoogleFonts.gafataTextTheme,
    'Galada': GoogleFonts.galadaTextTheme,
    'Galdeano': GoogleFonts.galdeanoTextTheme,
    'Galindo': GoogleFonts.galindoTextTheme,
    'Gamja Flower': GoogleFonts.gamjaFlowerTextTheme,
    'Gayathri': GoogleFonts.gayathriTextTheme,
    'Gelasio': GoogleFonts.gelasioTextTheme,
    'Gentium Basic': GoogleFonts.gentiumBasicTextTheme,
    'Gentium Book Basic': GoogleFonts.gentiumBookBasicTextTheme,
    'Geo': GoogleFonts.geoTextTheme,
    'Geostar': GoogleFonts.geostarTextTheme,
    'Geostar Fill': GoogleFonts.geostarFillTextTheme,
    'Germania One': GoogleFonts.germaniaOneTextTheme,
    'Gidugu': GoogleFonts.giduguTextTheme,
    'Gilda Display': GoogleFonts.gildaDisplayTextTheme,
    'Girassol': GoogleFonts.girassolTextTheme,
    'Give You Glory': GoogleFonts.giveYouGloryTextTheme,
    'Glass Antiqua': GoogleFonts.glassAntiquaTextTheme,
    'Glegoo': GoogleFonts.glegooTextTheme,
    'Gloria Hallelujah': GoogleFonts.gloriaHallelujahTextTheme,
    'Goblin One': GoogleFonts.goblinOneTextTheme,
    'Gochi Hand': GoogleFonts.gochiHandTextTheme,
    'Gorditas': GoogleFonts.gorditasTextTheme,
    'Gothic A1': GoogleFonts.gothicA1TextTheme,
    'Gotu': GoogleFonts.gotuTextTheme,
    'Goudy Bookletter 1911': GoogleFonts.goudyBookletter1911TextTheme,
    'Graduate': GoogleFonts.graduateTextTheme,
    'Grand Hotel': GoogleFonts.grandHotelTextTheme,
    'Gravitas One': GoogleFonts.gravitasOneTextTheme,
    'Great Vibes': GoogleFonts.greatVibesTextTheme,
    'Grenze': GoogleFonts.grenzeTextTheme,
    'Griffy': GoogleFonts.griffyTextTheme,
    'Gruppo': GoogleFonts.gruppoTextTheme,
    'Gudea': GoogleFonts.gudeaTextTheme,
    'Gugi': GoogleFonts.gugiTextTheme,
    'Gupter': GoogleFonts.gupterTextTheme,
    'Gurajada': GoogleFonts.gurajadaTextTheme,
    'Habibi': GoogleFonts.habibiTextTheme,
    'Halant': GoogleFonts.halantTextTheme,
    'Hammersmith One': GoogleFonts.hammersmithOneTextTheme,
    'Hanalei': GoogleFonts.hanaleiTextTheme,
    'Hanalei Fill': GoogleFonts.hanaleiFillTextTheme,
    'Handlee': GoogleFonts.handleeTextTheme,
    'Happy Monkey': GoogleFonts.happyMonkeyTextTheme,
    'Harmattan': GoogleFonts.harmattanTextTheme,
    'Headland One': GoogleFonts.headlandOneTextTheme,
    'Heebo': GoogleFonts.heeboTextTheme,
    'Henny Penny': GoogleFonts.hennyPennyTextTheme,
    'Hepta Slab': GoogleFonts.heptaSlabTextTheme,
    'Herr Von Muellerhoff': GoogleFonts.herrVonMuellerhoffTextTheme,
    'Hi Melody': GoogleFonts.hiMelodyTextTheme,
    'Hind': GoogleFonts.hindTextTheme,
    'Hind Guntur': GoogleFonts.hindGunturTextTheme,
    'Hind Madurai': GoogleFonts.hindMaduraiTextTheme,
    'Hind Siliguri': GoogleFonts.hindSiliguriTextTheme,
    'Hind Vadodara': GoogleFonts.hindVadodaraTextTheme,
    'Holtwood One SC': GoogleFonts.holtwoodOneScTextTheme,
    'Homemade Apple': GoogleFonts.homemadeAppleTextTheme,
    'Homenaje': GoogleFonts.homenajeTextTheme,
    'IBM Plex Mono': GoogleFonts.ibmPlexMonoTextTheme,
    'IBM Plex Sans': GoogleFonts.ibmPlexSansTextTheme,
    'IBM Plex Sans Condensed': GoogleFonts.ibmPlexSansCondensedTextTheme,
    'IBM Plex Serif': GoogleFonts.ibmPlexSerifTextTheme,
    'IM Fell DW Pica': GoogleFonts.imFellDwPicaTextTheme,
    'IM Fell DW Pica SC': GoogleFonts.imFellDwPicaScTextTheme,
    'IM Fell Double Pica': GoogleFonts.imFellDoublePicaTextTheme,
    'IM Fell Double Pica SC': GoogleFonts.imFellDoublePicaScTextTheme,
    'IM Fell English': GoogleFonts.imFellEnglishTextTheme,
    'IM Fell English SC': GoogleFonts.imFellEnglishScTextTheme,
    'IM Fell French Canon': GoogleFonts.imFellFrenchCanonTextTheme,
    'IM Fell French Canon SC': GoogleFonts.imFellFrenchCanonScTextTheme,
    'IM Fell Great Primer': GoogleFonts.imFellGreatPrimerTextTheme,
    'IM Fell Great Primer SC': GoogleFonts.imFellGreatPrimerScTextTheme,
    'Ibarra Real Nova': GoogleFonts.ibarraRealNovaTextTheme,
    'Iceberg': GoogleFonts.icebergTextTheme,
    'Iceland': GoogleFonts.icelandTextTheme,
    'Imprima': GoogleFonts.imprimaTextTheme,
    'Inconsolata': GoogleFonts.inconsolataTextTheme,
    'Inder': GoogleFonts.inderTextTheme,
    'Indie Flower': GoogleFonts.indieFlowerTextTheme,
    'Inika': GoogleFonts.inikaTextTheme,
    'Inknut Antiqua': GoogleFonts.inknutAntiquaTextTheme,
    'Inria Sans': GoogleFonts.inriaSansTextTheme,
    'Inria Serif': GoogleFonts.inriaSerifTextTheme,
    'Inter': GoogleFonts.interTextTheme,
    'Irish Grover': GoogleFonts.irishGroverTextTheme,
    'Istok Web': GoogleFonts.istokWebTextTheme,
    'Italiana': GoogleFonts.italianaTextTheme,
    'Italianno': GoogleFonts.italiannoTextTheme,
    'Itim': GoogleFonts.itimTextTheme,
    'Jacques Francois': GoogleFonts.jacquesFrancoisTextTheme,
    'Jacques Francois Shadow': GoogleFonts.jacquesFrancoisShadowTextTheme,
    'Jaldi': GoogleFonts.jaldiTextTheme,
    'Jim Nightshade': GoogleFonts.jimNightshadeTextTheme,
    'Jockey One': GoogleFonts.jockeyOneTextTheme,
    'Jolly Lodger': GoogleFonts.jollyLodgerTextTheme,
    'Jomhuria': GoogleFonts.jomhuriaTextTheme,
    'Jomolhari': GoogleFonts.jomolhariTextTheme,
    'Josefin Sans': GoogleFonts.josefinSansTextTheme,
    'Josefin Slab': GoogleFonts.josefinSlabTextTheme,
    'Joti One': GoogleFonts.jotiOneTextTheme,
    'Jua': GoogleFonts.juaTextTheme,
    'Judson': GoogleFonts.judsonTextTheme,
    'Julee': GoogleFonts.juleeTextTheme,
    'Julius Sans One': GoogleFonts.juliusSansOneTextTheme,
    'Junge': GoogleFonts.jungeTextTheme,
    'Jura': GoogleFonts.juraTextTheme,
    'Just Another Hand': GoogleFonts.justAnotherHandTextTheme,
    'Just Me Again Down Here': GoogleFonts.justMeAgainDownHereTextTheme,
    'K2D': GoogleFonts.k2dTextTheme,
    'Kadwa': GoogleFonts.kadwaTextTheme,
    'Kalam': GoogleFonts.kalamTextTheme,
    'Kameron': GoogleFonts.kameronTextTheme,
    'Kanit': GoogleFonts.kanitTextTheme,
    'Kantumruy': GoogleFonts.kantumruyTextTheme,
    'Karla': GoogleFonts.karlaTextTheme,
    'Karma': GoogleFonts.karmaTextTheme,
    'Katibeh': GoogleFonts.katibehTextTheme,
    'Kaushan Script': GoogleFonts.kaushanScriptTextTheme,
    'Kavivanar': GoogleFonts.kavivanarTextTheme,
    'Kavoon': GoogleFonts.kavoonTextTheme,
    'Kdam Thmor': GoogleFonts.kdamThmorTextTheme,
    'Keania One': GoogleFonts.keaniaOneTextTheme,
    'Kelly Slab': GoogleFonts.kellySlabTextTheme,
    'Kenia': GoogleFonts.keniaTextTheme,
    'Khand': GoogleFonts.khandTextTheme,
    'Khula': GoogleFonts.khulaTextTheme,
    'Kirang Haerang': GoogleFonts.kirangHaerangTextTheme,
    'Kite One': GoogleFonts.kiteOneTextTheme,
    'Knewave': GoogleFonts.knewaveTextTheme,
    'KoHo': GoogleFonts.koHoTextTheme,
    'Kodchasan': GoogleFonts.kodchasanTextTheme,
    'Kosugi': GoogleFonts.kosugiTextTheme,
    'Kosugi Maru': GoogleFonts.kosugiMaruTextTheme,
    'Kotta One': GoogleFonts.kottaOneTextTheme,
    'Kranky': GoogleFonts.krankyTextTheme,
    'Kreon': GoogleFonts.kreonTextTheme,
    'Kristi': GoogleFonts.kristiTextTheme,
    'Krona One': GoogleFonts.kronaOneTextTheme,
    'Krub': GoogleFonts.krubTextTheme,
    'Kulim Park': GoogleFonts.kulimParkTextTheme,
    'Kumar One': GoogleFonts.kumarOneTextTheme,
    'Kumar One Outline': GoogleFonts.kumarOneOutlineTextTheme,
    'Kurale': GoogleFonts.kuraleTextTheme,
    'La Belle Aurore': GoogleFonts.laBelleAuroreTextTheme,
    'Lacquer': GoogleFonts.lacquerTextTheme,
    'Laila': GoogleFonts.lailaTextTheme,
    'Lakki Reddy': GoogleFonts.lakkiReddyTextTheme,
    'Lalezar': GoogleFonts.lalezarTextTheme,
    'Lancelot': GoogleFonts.lancelotTextTheme,
    'Lateef': GoogleFonts.lateefTextTheme,
    'Lato': GoogleFonts.latoTextTheme,
    'League Script': GoogleFonts.leagueScriptTextTheme,
    'Leckerli One': GoogleFonts.leckerliOneTextTheme,
    'Ledger': GoogleFonts.ledgerTextTheme,
    'Lekton': GoogleFonts.lektonTextTheme,
    'Lemon': GoogleFonts.lemonTextTheme,
    'Lemonada': GoogleFonts.lemonadaTextTheme,
    'Lexend Deca': GoogleFonts.lexendDecaTextTheme,
    'Lexend Exa': GoogleFonts.lexendExaTextTheme,
    'Lexend Giga': GoogleFonts.lexendGigaTextTheme,
    'Lexend Mega': GoogleFonts.lexendMegaTextTheme,
    'Lexend Peta': GoogleFonts.lexendPetaTextTheme,
    'Lexend Tera': GoogleFonts.lexendTeraTextTheme,
    'Lexend Zetta': GoogleFonts.lexendZettaTextTheme,
    'Libre Barcode 128': GoogleFonts.libreBarcode128TextTheme,
    'Libre Barcode 128 Text': GoogleFonts.libreBarcode128TextTextTheme,
    'Libre Barcode 39': GoogleFonts.libreBarcode39TextTheme,
    'Libre Barcode 39 Extended': GoogleFonts.libreBarcode39ExtendedTextTheme,
    'Libre Barcode 39 Extended Text':
        GoogleFonts.libreBarcode39ExtendedTextTextTheme,
    'Libre Barcode 39 Text': GoogleFonts.libreBarcode39TextTextTheme,
    'Libre Baskerville': GoogleFonts.libreBaskervilleTextTheme,
    'Libre Caslon Display': GoogleFonts.libreCaslonDisplayTextTheme,
    'Libre Caslon Text': GoogleFonts.libreCaslonTextTextTheme,
    'Libre Franklin': GoogleFonts.libreFranklinTextTheme,
    'Life Savers': GoogleFonts.lifeSaversTextTheme,
    'Lilita One': GoogleFonts.lilitaOneTextTheme,
    'Lily Script One': GoogleFonts.lilyScriptOneTextTheme,
    'Limelight': GoogleFonts.limelightTextTheme,
    'Linden Hill': GoogleFonts.lindenHillTextTheme,
    'Literata': GoogleFonts.literataTextTheme,
    'Liu Jian Mao Cao': GoogleFonts.liuJianMaoCaoTextTheme,
    'Livvic': GoogleFonts.livvicTextTheme,
    'Lobster': GoogleFonts.lobsterTextTheme,
    'Lobster Two': GoogleFonts.lobsterTwoTextTheme,
    'Londrina Outline': GoogleFonts.londrinaOutlineTextTheme,
    'Londrina Shadow': GoogleFonts.londrinaShadowTextTheme,
    'Londrina Sketch': GoogleFonts.londrinaSketchTextTheme,
    'Londrina Solid': GoogleFonts.londrinaSolidTextTheme,
    'Long Cang': GoogleFonts.longCangTextTheme,
    'Lora': GoogleFonts.loraTextTheme,
    'Love Ya Like A Sister': GoogleFonts.loveYaLikeASisterTextTheme,
    'Loved by the King': GoogleFonts.lovedByTheKingTextTheme,
    'Lovers Quarrel': GoogleFonts.loversQuarrelTextTheme,
    'Luckiest Guy': GoogleFonts.luckiestGuyTextTheme,
    'Lusitana': GoogleFonts.lusitanaTextTheme,
    'Lustria': GoogleFonts.lustriaTextTheme,
    'M PLUS 1p': GoogleFonts.mPlus1pTextTheme,
    'M PLUS Rounded 1c': GoogleFonts.mPlusRounded1cTextTheme,
    'Ma Shan Zheng': GoogleFonts.maShanZhengTextTheme,
    'Macondo': GoogleFonts.macondoTextTheme,
    'Macondo Swash Caps': GoogleFonts.macondoSwashCapsTextTheme,
    'Mada': GoogleFonts.madaTextTheme,
    'Magra': GoogleFonts.magraTextTheme,
    'Maiden Orange': GoogleFonts.maidenOrangeTextTheme,
    'Maitree': GoogleFonts.maitreeTextTheme,
    'Major Mono Display': GoogleFonts.majorMonoDisplayTextTheme,
    'Mako': GoogleFonts.makoTextTheme,
    'Mali': GoogleFonts.maliTextTheme,
    'Mallanna': GoogleFonts.mallannaTextTheme,
    'Mandali': GoogleFonts.mandaliTextTheme,
    'Manjari': GoogleFonts.manjariTextTheme,
    'Manrope': GoogleFonts.manropeTextTheme,
    'Mansalva': GoogleFonts.mansalvaTextTheme,
    'Manuale': GoogleFonts.manualeTextTheme,
    'Marcellus': GoogleFonts.marcellusTextTheme,
    'Marcellus SC': GoogleFonts.marcellusScTextTheme,
    'Marck Script': GoogleFonts.marckScriptTextTheme,
    'Margarine': GoogleFonts.margarineTextTheme,
    'Markazi Text': GoogleFonts.markaziTextTextTheme,
    'Marko One': GoogleFonts.markoOneTextTheme,
    'Marmelad': GoogleFonts.marmeladTextTheme,
    'Martel': GoogleFonts.martelTextTheme,
    'Martel Sans': GoogleFonts.martelSansTextTheme,
    'Marvel': GoogleFonts.marvelTextTheme,
    'Mate': GoogleFonts.mateTextTheme,
    'Mate SC': GoogleFonts.mateScTextTheme,
    'Maven Pro': GoogleFonts.mavenProTextTheme,
    'McLaren': GoogleFonts.mcLarenTextTheme,
    'Meddon': GoogleFonts.meddonTextTheme,
    'MedievalSharp': GoogleFonts.medievalSharpTextTheme,
    'Medula One': GoogleFonts.medulaOneTextTheme,
    'Meera Inimai': GoogleFonts.meeraInimaiTextTheme,
    'Megrim': GoogleFonts.megrimTextTheme,
    'Meie Script': GoogleFonts.meieScriptTextTheme,
    'Merienda': GoogleFonts.meriendaTextTheme,
    'Merienda One': GoogleFonts.meriendaOneTextTheme,
    'Merriweather': GoogleFonts.merriweatherTextTheme,
    'Merriweather Sans': GoogleFonts.merriweatherSansTextTheme,
    'Metal Mania': GoogleFonts.metalManiaTextTheme,
    'Metamorphous': GoogleFonts.metamorphousTextTheme,
    'Metrophobic': GoogleFonts.metrophobicTextTheme,
    'Michroma': GoogleFonts.michromaTextTheme,
    'Milonga': GoogleFonts.milongaTextTheme,
    'Miltonian': GoogleFonts.miltonianTextTheme,
    'Miltonian Tattoo': GoogleFonts.miltonianTattooTextTheme,
    'Mina': GoogleFonts.minaTextTheme,
    'Miniver': GoogleFonts.miniverTextTheme,
    'Miriam Libre': GoogleFonts.miriamLibreTextTheme,
    'Mirza': GoogleFonts.mirzaTextTheme,
    'Miss Fajardose': GoogleFonts.missFajardoseTextTheme,
    'Mitr': GoogleFonts.mitrTextTheme,
    'Modak': GoogleFonts.modakTextTheme,
    'Modern Antiqua': GoogleFonts.modernAntiquaTextTheme,
    'Mogra': GoogleFonts.mograTextTheme,
    'Molengo': GoogleFonts.molengoTextTheme,
    'Molle': GoogleFonts.molleTextTheme,
    'Monda': GoogleFonts.mondaTextTheme,
    'Monofett': GoogleFonts.monofettTextTheme,
    'Monoton': GoogleFonts.monotonTextTheme,
    'Monsieur La Doulaise': GoogleFonts.monsieurLaDoulaiseTextTheme,
    'Montaga': GoogleFonts.montagaTextTheme,
    'Montez': GoogleFonts.montezTextTheme,
    'Montserrat': GoogleFonts.montserratTextTheme,
    'Montserrat Alternates': GoogleFonts.montserratAlternatesTextTheme,
    'Montserrat Subrayada': GoogleFonts.montserratSubrayadaTextTheme,
    'Mountains of Christmas': GoogleFonts.mountainsOfChristmasTextTheme,
    'Mouse Memoirs': GoogleFonts.mouseMemoirsTextTheme,
    'Mr Bedfort': GoogleFonts.mrBedfortTextTheme,
    'Mr Dafoe': GoogleFonts.mrDafoeTextTheme,
    'Mr De Haviland': GoogleFonts.mrDeHavilandTextTheme,
    'Mrs Saint Delafield': GoogleFonts.mrsSaintDelafieldTextTheme,
    'Mrs Sheppards': GoogleFonts.mrsSheppardsTextTheme,
    'Mukta': GoogleFonts.muktaTextTheme,
    'Mukta Mahee': GoogleFonts.muktaMaheeTextTheme,
    'Mukta Malar': GoogleFonts.muktaMalarTextTheme,
    'Mukta Vaani': GoogleFonts.muktaVaaniTextTheme,
    'Mulish': GoogleFonts.mulishTextTheme,
    'Mystery Quest': GoogleFonts.mysteryQuestTextTheme,
    'NTR': GoogleFonts.ntrTextTheme,
    'Nanum Brush Script': GoogleFonts.nanumBrushScriptTextTheme,
    'Nanum Gothic': GoogleFonts.nanumGothicTextTheme,
    'Nanum Gothic Coding': GoogleFonts.nanumGothicCodingTextTheme,
    'Nanum Myeongjo': GoogleFonts.nanumMyeongjoTextTheme,
    'Nanum Pen Script': GoogleFonts.nanumPenScriptTextTheme,
    'Neucha': GoogleFonts.neuchaTextTheme,
    'Neuton': GoogleFonts.neutonTextTheme,
    'New Rocker': GoogleFonts.newRockerTextTheme,
    'News Cycle': GoogleFonts.newsCycleTextTheme,
    'Niconne': GoogleFonts.niconneTextTheme,
    'Niramit': GoogleFonts.niramitTextTheme,
    'Nixie One': GoogleFonts.nixieOneTextTheme,
    'Nobile': GoogleFonts.nobileTextTheme,
    'Norican': GoogleFonts.noricanTextTheme,
    'Nosifer': GoogleFonts.nosiferTextTheme,
    'Notable': GoogleFonts.notableTextTheme,
    'Nothing You Could Do': GoogleFonts.nothingYouCouldDoTextTheme,
    'Noticia Text': GoogleFonts.noticiaTextTextTheme,
    'Noto Color Emoji Compat': GoogleFonts.notoColorEmojiCompatTextTheme,
    'Noto Sans': GoogleFonts.notoSansTextTheme,
    'Noto Serif': GoogleFonts.notoSerifTextTheme,
    'Nova Cut': GoogleFonts.novaCutTextTheme,
    'Nova Flat': GoogleFonts.novaFlatTextTheme,
    'Nova Mono': GoogleFonts.novaMonoTextTheme,
    'Nova Oval': GoogleFonts.novaOvalTextTheme,
    'Nova Round': GoogleFonts.novaRoundTextTheme,
    'Nova Script': GoogleFonts.novaScriptTextTheme,
    'Nova Slim': GoogleFonts.novaSlimTextTheme,
    'Nova Square': GoogleFonts.novaSquareTextTheme,
    'Numans': GoogleFonts.numansTextTheme,
    'Nunito': GoogleFonts.nunitoTextTheme,
    'Nunito Sans': GoogleFonts.nunitoSansTextTheme,
    'Odibee Sans': GoogleFonts.odibeeSansTextTheme,
    'Odor Mean Chey': GoogleFonts.odorMeanCheyTextTheme,
    'Offside': GoogleFonts.offsideTextTheme,
    'Old Standard TT': GoogleFonts.oldStandardTtTextTheme,
    'Oldenburg': GoogleFonts.oldenburgTextTheme,
    'Oleo Script': GoogleFonts.oleoScriptTextTheme,
    'Oleo Script Swash Caps': GoogleFonts.oleoScriptSwashCapsTextTheme,
    'Open Sans': GoogleFonts.openSansTextTheme,
    'Open Sans Condensed': GoogleFonts.openSansCondensedTextTheme,
    'Oranienbaum': GoogleFonts.oranienbaumTextTheme,
    'Orbitron': GoogleFonts.orbitronTextTheme,
    'Oregano': GoogleFonts.oreganoTextTheme,
    'Orienta': GoogleFonts.orientaTextTheme,
    'Original Surfer': GoogleFonts.originalSurferTextTheme,
    'Oswald': GoogleFonts.oswaldTextTheme,
    'Over the Rainbow': GoogleFonts.overTheRainbowTextTheme,
    'Overlock': GoogleFonts.overlockTextTheme,
    'Overlock SC': GoogleFonts.overlockScTextTheme,
    'Overpass': GoogleFonts.overpassTextTheme,
    'Overpass Mono': GoogleFonts.overpassMonoTextTheme,
    'Ovo': GoogleFonts.ovoTextTheme,
    'Oxanium': GoogleFonts.oxaniumTextTheme,
    'Oxygen': GoogleFonts.oxygenTextTheme,
    'Oxygen Mono': GoogleFonts.oxygenMonoTextTheme,
    'PT Mono': GoogleFonts.ptMonoTextTheme,
    'PT Sans': GoogleFonts.ptSansTextTheme,
    'PT Sans Caption': GoogleFonts.ptSansCaptionTextTheme,
    'PT Sans Narrow': GoogleFonts.ptSansNarrowTextTheme,
    'PT Serif': GoogleFonts.ptSerifTextTheme,
    'PT Serif Caption': GoogleFonts.ptSerifCaptionTextTheme,
    'Pacifico': GoogleFonts.pacificoTextTheme,
    'Padauk': GoogleFonts.padaukTextTheme,
    'Palanquin': GoogleFonts.palanquinTextTheme,
    'Palanquin Dark': GoogleFonts.palanquinDarkTextTheme,
    'Pangolin': GoogleFonts.pangolinTextTheme,
    'Paprika': GoogleFonts.paprikaTextTheme,
    'Parisienne': GoogleFonts.parisienneTextTheme,
    'Passero One': GoogleFonts.passeroOneTextTheme,
    'Passion One': GoogleFonts.passionOneTextTheme,
    'Pathway Gothic One': GoogleFonts.pathwayGothicOneTextTheme,
    'Patrick Hand': GoogleFonts.patrickHandTextTheme,
    'Patrick Hand SC': GoogleFonts.patrickHandScTextTheme,
    'Pattaya': GoogleFonts.pattayaTextTheme,
    'Patua One': GoogleFonts.patuaOneTextTheme,
    'Pavanam': GoogleFonts.pavanamTextTheme,
    'Paytone One': GoogleFonts.paytoneOneTextTheme,
    'Peddana': GoogleFonts.peddanaTextTheme,
    'Peralta': GoogleFonts.peraltaTextTheme,
    'Permanent Marker': GoogleFonts.permanentMarkerTextTheme,
    'Petit Formal Script': GoogleFonts.petitFormalScriptTextTheme,
    'Petrona': GoogleFonts.petronaTextTheme,
    'Philosopher': GoogleFonts.philosopherTextTheme,
    'Piedra': GoogleFonts.piedraTextTheme,
    'Pinyon Script': GoogleFonts.pinyonScriptTextTheme,
    'Pirata One': GoogleFonts.pirataOneTextTheme,
    'Plaster': GoogleFonts.plasterTextTheme,
    'Play': GoogleFonts.playTextTheme,
    'Playball': GoogleFonts.playballTextTheme,
    'Playfair Display': GoogleFonts.playfairDisplayTextTheme,
    'Playfair Display SC': GoogleFonts.playfairDisplayScTextTheme,
    'Podkova': GoogleFonts.podkovaTextTheme,
    'Poiret One': GoogleFonts.poiretOneTextTheme,
    'Poller One': GoogleFonts.pollerOneTextTheme,
    'Poly': GoogleFonts.polyTextTheme,
    'Pompiere': GoogleFonts.pompiereTextTheme,
    'Pontano Sans': GoogleFonts.pontanoSansTextTheme,
    'Poor Story': GoogleFonts.poorStoryTextTheme,
    'Poppins': GoogleFonts.poppinsTextTheme,
    'Port Lligat Sans': GoogleFonts.portLligatSansTextTheme,
    'Port Lligat Slab': GoogleFonts.portLligatSlabTextTheme,
    'Pragati Narrow': GoogleFonts.pragatiNarrowTextTheme,
    'Prata': GoogleFonts.prataTextTheme,
    'Press Start 2P': GoogleFonts.pressStart2pTextTheme,
    'Pridi': GoogleFonts.pridiTextTheme,
    'Princess Sofia': GoogleFonts.princessSofiaTextTheme,
    'Prociono': GoogleFonts.procionoTextTheme,
    'Prompt': GoogleFonts.promptTextTheme,
    'Prosto One': GoogleFonts.prostoOneTextTheme,
    'Proza Libre': GoogleFonts.prozaLibreTextTheme,
    'Public Sans': GoogleFonts.publicSansTextTheme,
    'Puritan': GoogleFonts.puritanTextTheme,
    'Purple Purse': GoogleFonts.purplePurseTextTheme,
    'Quando': GoogleFonts.quandoTextTheme,
    'Quantico': GoogleFonts.quanticoTextTheme,
    'Quattrocento': GoogleFonts.quattrocentoTextTheme,
    'Quattrocento Sans': GoogleFonts.quattrocentoSansTextTheme,
    'Questrial': GoogleFonts.questrialTextTheme,
    'Quicksand': GoogleFonts.quicksandTextTheme,
    'Quintessential': GoogleFonts.quintessentialTextTheme,
    'Qwigley': GoogleFonts.qwigleyTextTheme,
    'Racing Sans One': GoogleFonts.racingSansOneTextTheme,
    'Radley': GoogleFonts.radleyTextTheme,
    'Rajdhani': GoogleFonts.rajdhaniTextTheme,
    'Rakkas': GoogleFonts.rakkasTextTheme,
    'Raleway': GoogleFonts.ralewayTextTheme,
    'Raleway Dots': GoogleFonts.ralewayDotsTextTheme,
    'Ramabhadra': GoogleFonts.ramabhadraTextTheme,
    'Ramaraja': GoogleFonts.ramarajaTextTheme,
    'Rambla': GoogleFonts.ramblaTextTheme,
    'Rammetto One': GoogleFonts.rammettoOneTextTheme,
    'Ranchers': GoogleFonts.ranchersTextTheme,
    'Rancho': GoogleFonts.ranchoTextTheme,
    'Ranga': GoogleFonts.rangaTextTheme,
    'Rasa': GoogleFonts.rasaTextTheme,
    'Rationale': GoogleFonts.rationaleTextTheme,
    'Ravi Prakash': GoogleFonts.raviPrakashTextTheme,
    'Red Hat Display': GoogleFonts.redHatDisplayTextTheme,
    'Red Hat Text': GoogleFonts.redHatTextTextTheme,
    'Redressed': GoogleFonts.redressedTextTheme,
    'Reem Kufi': GoogleFonts.reemKufiTextTheme,
    'Reenie Beanie': GoogleFonts.reenieBeanieTextTheme,
    'Revalia': GoogleFonts.revaliaTextTheme,
    'Rhodium Libre': GoogleFonts.rhodiumLibreTextTheme,
    'Ribeye': GoogleFonts.ribeyeTextTheme,
    'Ribeye Marrow': GoogleFonts.ribeyeMarrowTextTheme,
    'Righteous': GoogleFonts.righteousTextTheme,
    'Risque': GoogleFonts.risqueTextTheme,
    'Roboto': GoogleFonts.robotoTextTheme,
    'Roboto Condensed': GoogleFonts.robotoCondensedTextTheme,
    'Roboto Mono': GoogleFonts.robotoMonoTextTheme,
    'Roboto Slab': GoogleFonts.robotoSlabTextTheme,
    'Rochester': GoogleFonts.rochesterTextTheme,
    'Rock Salt': GoogleFonts.rockSaltTextTheme,
    'Rokkitt': GoogleFonts.rokkittTextTheme,
    'Romanesco': GoogleFonts.romanescoTextTheme,
    'Ropa Sans': GoogleFonts.ropaSansTextTheme,
    'Rosario': GoogleFonts.rosarioTextTheme,
    'Rosarivo': GoogleFonts.rosarivoTextTheme,
    'Rouge Script': GoogleFonts.rougeScriptTextTheme,
    'Rozha One': GoogleFonts.rozhaOneTextTheme,
    'Rubik': GoogleFonts.rubikTextTheme,
    'Rubik Mono One': GoogleFonts.rubikMonoOneTextTheme,
    'Ruda': GoogleFonts.rudaTextTheme,
    'Rufina': GoogleFonts.rufinaTextTheme,
    'Ruge Boogie': GoogleFonts.rugeBoogieTextTheme,
    'Ruluko': GoogleFonts.rulukoTextTheme,
    'Rum Raisin': GoogleFonts.rumRaisinTextTheme,
    'Ruslan Display': GoogleFonts.ruslanDisplayTextTheme,
    'Russo One': GoogleFonts.russoOneTextTheme,
    'Ruthie': GoogleFonts.ruthieTextTheme,
    'Rye': GoogleFonts.ryeTextTheme,
    'Sacramento': GoogleFonts.sacramentoTextTheme,
    'Sahitya': GoogleFonts.sahityaTextTheme,
    'Sail': GoogleFonts.sailTextTheme,
    'Saira': GoogleFonts.sairaTextTheme,
    'Saira Condensed': GoogleFonts.sairaCondensedTextTheme,
    'Saira Extra Condensed': GoogleFonts.sairaExtraCondensedTextTheme,
    'Saira Semi Condensed': GoogleFonts.sairaSemiCondensedTextTheme,
    'Saira Stencil One': GoogleFonts.sairaStencilOneTextTheme,
    'Salsa': GoogleFonts.salsaTextTheme,
    'Sanchez': GoogleFonts.sanchezTextTheme,
    'Sancreek': GoogleFonts.sancreekTextTheme,
    'Sansita': GoogleFonts.sansitaTextTheme,
    'Sarabun': GoogleFonts.sarabunTextTheme,
    'Sarala': GoogleFonts.saralaTextTheme,
    'Sarina': GoogleFonts.sarinaTextTheme,
    'Sarpanch': GoogleFonts.sarpanchTextTheme,
    'Satisfy': GoogleFonts.satisfyTextTheme,
    'Sawarabi Gothic': GoogleFonts.sawarabiGothicTextTheme,
    'Sawarabi Mincho': GoogleFonts.sawarabiMinchoTextTheme,
    'Scada': GoogleFonts.scadaTextTheme,
    'Scheherazade': GoogleFonts.scheherazadeTextTheme,
    'Schoolbell': GoogleFonts.schoolbellTextTheme,
    'Scope One': GoogleFonts.scopeOneTextTheme,
    'Seaweed Script': GoogleFonts.seaweedScriptTextTheme,
    'Secular One': GoogleFonts.secularOneTextTheme,
    'Sedgwick Ave': GoogleFonts.sedgwickAveTextTheme,
    'Sedgwick Ave Display': GoogleFonts.sedgwickAveDisplayTextTheme,
    'Sen': GoogleFonts.senTextTheme,
    'Sevillana': GoogleFonts.sevillanaTextTheme,
    'Seymour One': GoogleFonts.seymourOneTextTheme,
    'Shadows Into Light': GoogleFonts.shadowsIntoLightTextTheme,
    'Shadows Into Light Two': GoogleFonts.shadowsIntoLightTwoTextTheme,
    'Shanti': GoogleFonts.shantiTextTheme,
    'Share': GoogleFonts.shareTextTheme,
    'Share Tech': GoogleFonts.shareTechTextTheme,
    'Share Tech Mono': GoogleFonts.shareTechMonoTextTheme,
    'Shojumaru': GoogleFonts.shojumaruTextTheme,
    'Short Stack': GoogleFonts.shortStackTextTheme,
    'Shrikhand': GoogleFonts.shrikhandTextTheme,
    'Sigmar One': GoogleFonts.sigmarOneTextTheme,
    'Signika': GoogleFonts.signikaTextTheme,
    'Signika Negative': GoogleFonts.signikaNegativeTextTheme,
    'Simonetta': GoogleFonts.simonettaTextTheme,
    'Single Day': GoogleFonts.singleDayTextTheme,
    'Sintony': GoogleFonts.sintonyTextTheme,
    'Sirin Stencil': GoogleFonts.sirinStencilTextTheme,
    'Six Caps': GoogleFonts.sixCapsTextTheme,
    'Skranji': GoogleFonts.skranjiTextTheme,
    'Slabo 13px': GoogleFonts.slabo13pxTextTheme,
    'Slabo 27px': GoogleFonts.slabo27pxTextTheme,
    'Slackey': GoogleFonts.slackeyTextTheme,
    'Smokum': GoogleFonts.smokumTextTheme,
    'Smythe': GoogleFonts.smytheTextTheme,
    'Sniglet': GoogleFonts.snigletTextTheme,
    'Snippet': GoogleFonts.snippetTextTheme,
    'Snowburst One': GoogleFonts.snowburstOneTextTheme,
    'Sofadi One': GoogleFonts.sofadiOneTextTheme,
    'Sofia': GoogleFonts.sofiaTextTheme,
    'Solway': GoogleFonts.solwayTextTheme,
    'Song Myung': GoogleFonts.songMyungTextTheme,
    'Sonsie One': GoogleFonts.sonsieOneTextTheme,
    'Sorts Mill Goudy': GoogleFonts.sortsMillGoudyTextTheme,
    'Source Code Pro': GoogleFonts.sourceCodeProTextTheme,
    'Source Sans Pro': GoogleFonts.sourceSansProTextTheme,
    'Source Serif Pro': GoogleFonts.sourceSerifProTextTheme,
    'Space Mono': GoogleFonts.spaceMonoTextTheme,
    'Spartan': GoogleFonts.spartanTextTheme,
    'Special Elite': GoogleFonts.specialEliteTextTheme,
    'Spectral': GoogleFonts.spectralTextTheme,
    'Spectral SC': GoogleFonts.spectralScTextTheme,
    'Spicy Rice': GoogleFonts.spicyRiceTextTheme,
    'Spinnaker': GoogleFonts.spinnakerTextTheme,
    'Spirax': GoogleFonts.spiraxTextTheme,
    'Squada One': GoogleFonts.squadaOneTextTheme,
    'Sree Krushnadevaraya': GoogleFonts.sreeKrushnadevarayaTextTheme,
    'Sriracha': GoogleFonts.srirachaTextTheme,
    'Srisakdi': GoogleFonts.srisakdiTextTheme,
    'Staatliches': GoogleFonts.staatlichesTextTheme,
    'Stalemate': GoogleFonts.stalemateTextTheme,
    'Stalinist One': GoogleFonts.stalinistOneTextTheme,
    'Stardos Stencil': GoogleFonts.stardosStencilTextTheme,
    'Stint Ultra Condensed': GoogleFonts.stintUltraCondensedTextTheme,
    'Stint Ultra Expanded': GoogleFonts.stintUltraExpandedTextTheme,
    'Stoke': GoogleFonts.stokeTextTheme,
    'Strait': GoogleFonts.straitTextTheme,
    'Stylish': GoogleFonts.stylishTextTheme,
    'Sue Ellen Francisco': GoogleFonts.sueEllenFranciscoTextTheme,
    'Suez One': GoogleFonts.suezOneTextTheme,
    'Sulphur Point': GoogleFonts.sulphurPointTextTheme,
    'Sumana': GoogleFonts.sumanaTextTheme,
    'Sunflower': GoogleFonts.sunflowerTextTheme,
    'Sunshiney': GoogleFonts.sunshineyTextTheme,
    'Supermercado One': GoogleFonts.supermercadoOneTextTheme,
    'Sura': GoogleFonts.suraTextTheme,
    'Suranna': GoogleFonts.surannaTextTheme,
    'Suravaram': GoogleFonts.suravaramTextTheme,
    'Swanky and Moo Moo': GoogleFonts.swankyAndMooMooTextTheme,
    'Syncopate': GoogleFonts.syncopateTextTheme,
    'Tajawal': GoogleFonts.tajawalTextTheme,
    'Tangerine': GoogleFonts.tangerineTextTheme,
    'Tauri': GoogleFonts.tauriTextTheme,
    'Taviraj': GoogleFonts.tavirajTextTheme,
    'Teko': GoogleFonts.tekoTextTheme,
    'Telex': GoogleFonts.telexTextTheme,
    'Tenali Ramakrishna': GoogleFonts.tenaliRamakrishnaTextTheme,
    'Tenor Sans': GoogleFonts.tenorSansTextTheme,
    'Text Me One': GoogleFonts.textMeOneTextTheme,
    'Thasadith': GoogleFonts.thasadithTextTheme,
    'The Girl Next Door': GoogleFonts.theGirlNextDoorTextTheme,
    'Tienne': GoogleFonts.tienneTextTheme,
    'Tillana': GoogleFonts.tillanaTextTheme,
    'Timmana': GoogleFonts.timmanaTextTheme,
    'Tinos': GoogleFonts.tinosTextTheme,
    'Titan One': GoogleFonts.titanOneTextTheme,
    'Titillium Web': GoogleFonts.titilliumWebTextTheme,
    'Tomorrow': GoogleFonts.tomorrowTextTheme,
    'Trade Winds': GoogleFonts.tradeWindsTextTheme,
    'Trirong': GoogleFonts.trirongTextTheme,
    'Trocchi': GoogleFonts.trocchiTextTheme,
    'Trochut': GoogleFonts.trochutTextTheme,
    'Trykker': GoogleFonts.trykkerTextTheme,
    'Tulpen One': GoogleFonts.tulpenOneTextTheme,
    'Turret Road': GoogleFonts.turretRoadTextTheme,
    'Ubuntu': GoogleFonts.ubuntuTextTheme,
    'Ubuntu Condensed': GoogleFonts.ubuntuCondensedTextTheme,
    'Ubuntu Mono': GoogleFonts.ubuntuMonoTextTheme,
    'Ultra': GoogleFonts.ultraTextTheme,
    'Uncial Antiqua': GoogleFonts.uncialAntiquaTextTheme,
    'Underdog': GoogleFonts.underdogTextTheme,
    'Unica One': GoogleFonts.unicaOneTextTheme,
    'UnifrakturCook': GoogleFonts.unifrakturCookTextTheme,
    'UnifrakturMaguntia': GoogleFonts.unifrakturMaguntiaTextTheme,
    'Unkempt': GoogleFonts.unkemptTextTheme,
    'Unlock': GoogleFonts.unlockTextTheme,
    'Unna': GoogleFonts.unnaTextTheme,
    'VT323': GoogleFonts.vt323TextTheme,
    'Vampiro One': GoogleFonts.vampiroOneTextTheme,
    'Varela': GoogleFonts.varelaTextTheme,
    'Varela Round': GoogleFonts.varelaRoundTextTheme,
    'Vast Shadow': GoogleFonts.vastShadowTextTheme,
    'Vesper Libre': GoogleFonts.vesperLibreTextTheme,
    'Viaoda Libre': GoogleFonts.viaodaLibreTextTheme,
    'Vibes': GoogleFonts.vibesTextTheme,
    'Vibur': GoogleFonts.viburTextTheme,
    'Vidaloka': GoogleFonts.vidalokaTextTheme,
    'Viga': GoogleFonts.vigaTextTheme,
    'Voces': GoogleFonts.vocesTextTheme,
    'Volkhov': GoogleFonts.volkhovTextTheme,
    'Vollkorn': GoogleFonts.vollkornTextTheme,
    'Vollkorn SC': GoogleFonts.vollkornScTextTheme,
    'Voltaire': GoogleFonts.voltaireTextTheme,
    'Waiting for the Sunrise': GoogleFonts.waitingForTheSunriseTextTheme,
    'Wallpoet': GoogleFonts.wallpoetTextTheme,
    'Walter Turncoat': GoogleFonts.walterTurncoatTextTheme,
    'Warnes': GoogleFonts.warnesTextTheme,
    'Wellfleet': GoogleFonts.wellfleetTextTheme,
    'Wendy One': GoogleFonts.wendyOneTextTheme,
    'Wire One': GoogleFonts.wireOneTextTheme,
    'Work Sans': GoogleFonts.workSansTextTheme,
    'Yanone Kaffeesatz': GoogleFonts.yanoneKaffeesatzTextTheme,
    'Yantramanav': GoogleFonts.yantramanavTextTheme,
    'Yatra One': GoogleFonts.yatraOneTextTheme,
    'Yellowtail': GoogleFonts.yellowtailTextTheme,
    'Yeon Sung': GoogleFonts.yeonSungTextTheme,
    'Yeseva One': GoogleFonts.yesevaOneTextTheme,
    'Yesteryear': GoogleFonts.yesteryearTextTheme,
    'Yrsa': GoogleFonts.yrsaTextTheme,
    'ZCOOL KuaiLe': GoogleFonts.zcoolKuaiLeTextTheme,
    'ZCOOL QingKe HuangYou': GoogleFonts.zcoolQingKeHuangYouTextTheme,
    'ZCOOL XiaoWei': GoogleFonts.zcoolXiaoWeiTextTheme,
    'Zeyada': GoogleFonts.zeyadaTextTheme,
    'Zhi Mang Xing': GoogleFonts.zhiMangXingTextTheme,
    'Zilla Slab': GoogleFonts.zillaSlabTextTheme,
    'Zilla Slab Highlight': GoogleFonts.zillaSlabHighlightTextTheme,
  };
}
